#ifndef FRI_PINNING_VECTORS_HPP
#define FRI_PINNING_VECTORS_HPP

/*****************************************************************************
 *                    DO NOT EDIT THIS FILE MANUALLY!                        *
 *****************************************************************************
 *
 * This file is AUTO-GENERATED by generate-fri-vectors.sh
 * To regenerate after FRI changes:
 *     ./generate-fri-vectors.sh
 * Then copy the output into this file.
 * 
 * These values are extracted from SimpleLeft_0.json proof output and used
 * to validate that FRI produces consistent, expected output.
 *
 *****************************************************************************/

#include <array>
#include <cstdint>

namespace FriPinningVectors {

namespace SimpleLeft {

    //=========================================================================
    // FRI Configuration (from SimpleLeft.starkinfo.json)
    //=========================================================================

    /// Base domain size: 2^N_BITS = 8 rows
    constexpr uint64_t N_BITS = 3;

    /// Extended domain size: 2^N_BITS_EXT = 16 (blowup factor 2)
    constexpr uint64_t N_BITS_EXT = 4;

    /// Number of FRI queries for soundness
    constexpr uint64_t N_QUERIES = 228;

    /// Proof-of-work grinding bits
    constexpr uint64_t POW_BITS = 16;

    /// Merkle tree branching factor
    constexpr uint64_t MERKLE_ARITY = 4;

    /// Transcript (Fiat-Shamir) arity
    constexpr uint64_t TRANSCRIPT_ARITY = 4;

    /// Merkle tree last level verification depth
    constexpr uint64_t LAST_LEVEL_VERIFICATION = 2;

    /// Whether to hash polynomial commitments
    constexpr bool HASH_COMMITS = true;

    /// Whether using custom Merkle tree
    constexpr bool MERKLE_TREE_CUSTOM = true;

    /// FRI step configuration: single step reducing to 2^4 = 16 elements
    constexpr uint64_t NUM_FRI_STEPS = 1;
    constexpr std::array<uint64_t, 1> FRI_STEPS = {4};

    //=========================================================================
    // Expected FRI Output (from SimpleLeft_0.json)
    //=========================================================================

    /// Final polynomial after all FRI folding steps.
    /// Structure: 16 cubic extension elements = 48 Goldilocks field elements.
    /// Layout: [elem0_c0, elem0_c1, elem0_c2, elem1_c0, elem1_c1, elem1_c2, ...]
    constexpr std::array<uint64_t, 48> EXPECTED_FINAL_POL = {
        // Element 0
        3055503030217023883ULL,
        14674508583309298785ULL,
        5885849117767276278ULL,
        // Element 1
        13701831255698438944ULL,
        1283723217496151905ULL,
        6787061737207648806ULL,
        // Element 2
        1490285254039880334ULL,
        12206638945089264610ULL,
        4028039824881281066ULL,
        // Element 3
        6173674811141161353ULL,
        12727931143765845850ULL,
        11772504568132636170ULL,
        // Element 4
        2124711334127787032ULL,
        2422792798526012876ULL,
        595475889981943084ULL,
        // Element 5
        12895309280498340374ULL,
        10209758780222158475ULL,
        11026945906801590302ULL,
        // Element 6
        7932333378049291554ULL,
        11698649812757253058ULL,
        65233997353509573ULL,
        // Element 7
        8522747463959870547ULL,
        12526681977083944153ULL,
        8187629827557060993ULL,
        // Element 8
        15943641703712512390ULL,
        13900674231866633987ULL,
        9119815241417913437ULL,
        // Element 9
        13214328069786755482ULL,
        1290362087763361579ULL,
        15374365308707279671ULL,
        // Element 10
        14555069521905791416ULL,
        12285886796485120627ULL,
        14952573041881450266ULL,
        // Element 11
        7489272786740350018ULL,
        184279497294762181ULL,
        6702168602610022660ULL,
        // Element 12
        2872310693891620498ULL,
        18442687036345179693ULL,
        12600134693347240975ULL,
        // Element 13
        15762660494228645950ULL,
        1089223122280328124ULL,
        12538857081211527031ULL,
        // Element 14
        3260775988529739921ULL,
        3467800841604774028ULL,
        5041750969204501126ULL,
        // Element 15
        10368294881249253002ULL,
        12894191081247816755ULL,
        16792827882436518814ULL
    };

    /// Expected grinding nonce (proof-of-work result).
    /// This value satisfies: hash(challenge || nonce) has POW_BITS leading zeros.
    constexpr uint64_t EXPECTED_NONCE = 56;

    /// Expected Poseidon2 hash of EXPECTED_FINAL_POL (4 Goldilocks elements).
    /// Computed using Poseidon2Goldilocks<16>::linear_hash_seq over all 48 elements.
    constexpr std::array<uint64_t, 4> EXPECTED_FINAL_POL_HASH = {
        16201618454940366509ULL,
        9223689653289312170ULL,
        6707438330426141909ULL,
        10762121192969877648ULL
    };

    /// SHA256 checksum of EXPECTED_FINAL_POL as comma-separated decimal strings.
    /// Used for quick validation without element-by-element comparison.
    constexpr const char* const EXPECTED_FINAL_POL_CHECKSUM =
        "45f67c58cbbac0383eb7d29cef8e93a12a18aa5520dc3a346369b6dacaedf921";

}  // namespace SimpleLeft

}  // namespace FriPinningVectors

#endif  // FRI_PINNING_VECTORS_HPP
