#ifndef FRI_PINNING_VECTORS_HPP
#define FRI_PINNING_VECTORS_HPP

/*****************************************************************************
 *                    DO NOT EDIT THIS FILE MANUALLY!                        *
 *****************************************************************************
 *
 * This file is AUTO-GENERATED by generate-fri-vectors.sh
 * To regenerate after FRI changes:
 *     ./generate-fri-vectors.sh
 * Then copy the output into this file.
 * 
 * These values are extracted from SimpleLeft_0.json proof output and used
 * to validate that FRI produces consistent, expected output.
 *
 *****************************************************************************/

#include <array>
#include <cstdint>

namespace FriPinningVectors {

namespace SimpleLeft {

    //=========================================================================
    // FRI Configuration (from SimpleLeft.starkinfo.json)
    //=========================================================================

    /// Base domain size: 2^N_BITS = 8 rows
    constexpr uint64_t N_BITS = 3;

    /// Extended domain size: 2^N_BITS_EXT = 16 (blowup factor 2)
    constexpr uint64_t N_BITS_EXT = 4;

    /// Number of FRI queries for soundness
    constexpr uint64_t N_QUERIES = 228;

    /// Proof-of-work grinding bits
    constexpr uint64_t POW_BITS = 16;

    /// Merkle tree branching factor
    constexpr uint64_t MERKLE_ARITY = 4;

    /// Transcript (Fiat-Shamir) arity
    constexpr uint64_t TRANSCRIPT_ARITY = 4;

    /// Merkle tree last level verification depth
    constexpr uint64_t LAST_LEVEL_VERIFICATION = 2;

    /// Whether to hash polynomial commitments
    constexpr bool HASH_COMMITS = true;

    /// Whether using custom Merkle tree
    constexpr bool MERKLE_TREE_CUSTOM = true;

    /// FRI step configuration: single step reducing to 2^4 = 16 elements
    constexpr uint64_t NUM_FRI_STEPS = 1;
    constexpr std::array<uint64_t, 1> FRI_STEPS = {4};

    //=========================================================================
    // FRI Input Vectors (captured from gen_proof.hpp with CAPTURE_TEST_VECTORS)
    //=========================================================================
    // NOTE: For SimpleLeft, the input polynomial equals the output polynomial
    // because the AIR is small enough that no FRI folding actually occurs.
    // This is expected behavior and validates deterministic proof generation.

    /// Input polynomial to FRI (before any folding).
    /// For SimpleLeft: identical to EXPECTED_FINAL_POL (no folding needed).
    constexpr std::array<uint64_t, 48> FRI_INPUT_POLYNOMIAL = {
        3055503030217023883ULL, 14674508583309298785ULL, 5885849117767276278ULL,  // Element 0
        13701831255698438944ULL, 1283723217496151905ULL, 6787061737207648806ULL,  // Element 1
        1490285254039880334ULL, 12206638945089264610ULL, 4028039824881281066ULL,  // Element 2
        6173674811141161353ULL, 12727931143765845850ULL, 11772504568132636170ULL,  // Element 3
        2124711334127787032ULL, 2422792798526012876ULL, 595475889981943084ULL,  // Element 4
        12895309280498340374ULL, 10209758780222158475ULL, 11026945906801590302ULL,  // Element 5
        7932333378049291554ULL, 11698649812757253058ULL, 65233997353509573ULL,  // Element 6
        8522747463959870547ULL, 12526681977083944153ULL, 8187629827557060993ULL,  // Element 7
        15943641703712512390ULL, 13900674231866633987ULL, 9119815241417913437ULL,  // Element 8
        13214328069786755482ULL, 1290362087763361579ULL, 15374365308707279671ULL,  // Element 9
        14555069521905791416ULL, 12285886796485120627ULL, 14952573041881450266ULL,  // Element 10
        7489272786740350018ULL, 184279497294762181ULL, 6702168602610022660ULL,  // Element 11
        2872310693891620498ULL, 18442687036345179693ULL, 12600134693347240975ULL,  // Element 12
        15762660494228645950ULL, 1089223122280328124ULL, 12538857081211527031ULL,  // Element 13
        3260775988529739921ULL, 3467800841604774028ULL, 5041750969204501126ULL,  // Element 14
        10368294881249253002ULL, 12894191081247816755ULL, 16792827882436518814ULL   // Element 15
    };

    /// Hash of input polynomial (Poseidon2).
    /// For SimpleLeft: identical to EXPECTED_FINAL_POL_HASH.
    constexpr std::array<uint64_t, 4> FRI_INPUT_POL_HASH = {
        16201618454940366509ULL,
        9223689653289312170ULL,
        6707438330426141909ULL,
        10762121192969877648ULL
    };

    /// FRI folding challenges (one per FRI step).
    /// Each challenge is a cubic extension field element (3 Goldilocks values).
    constexpr std::array<std::array<uint64_t, 3>, 1> FRI_CHALLENGES = {{
        {5360955783996970004ULL, 3623636231864186898ULL, 10531370013360693355ULL}  // Challenge 0
    }};

    /// Grinding challenge (used for proof-of-work).
    /// For SimpleLeft with single FRI step, equals the last FRI challenge.
    constexpr std::array<uint64_t, 3> GRINDING_CHALLENGE = {
        5360955783996970004ULL,
        3623636231864186898ULL,
        10531370013360693355ULL
    };

    //=========================================================================
    // Expected FRI Output (from SimpleLeft_0.json)
    //=========================================================================

    /// Final polynomial after all FRI folding steps.
    /// Structure: 16 cubic extension elements = 48 Goldilocks field elements.
    /// Layout: [elem0_c0, elem0_c1, elem0_c2, elem1_c0, elem1_c1, elem1_c2, ...]
    constexpr std::array<uint64_t, 48> EXPECTED_FINAL_POL = {
        // Element 0
        3055503030217023883ULL,
        14674508583309298785ULL,
        5885849117767276278ULL,
        // Element 1
        13701831255698438944ULL,
        1283723217496151905ULL,
        6787061737207648806ULL,
        // Element 2
        1490285254039880334ULL,
        12206638945089264610ULL,
        4028039824881281066ULL,
        // Element 3
        6173674811141161353ULL,
        12727931143765845850ULL,
        11772504568132636170ULL,
        // Element 4
        2124711334127787032ULL,
        2422792798526012876ULL,
        595475889981943084ULL,
        // Element 5
        12895309280498340374ULL,
        10209758780222158475ULL,
        11026945906801590302ULL,
        // Element 6
        7932333378049291554ULL,
        11698649812757253058ULL,
        65233997353509573ULL,
        // Element 7
        8522747463959870547ULL,
        12526681977083944153ULL,
        8187629827557060993ULL,
        // Element 8
        15943641703712512390ULL,
        13900674231866633987ULL,
        9119815241417913437ULL,
        // Element 9
        13214328069786755482ULL,
        1290362087763361579ULL,
        15374365308707279671ULL,
        // Element 10
        14555069521905791416ULL,
        12285886796485120627ULL,
        14952573041881450266ULL,
        // Element 11
        7489272786740350018ULL,
        184279497294762181ULL,
        6702168602610022660ULL,
        // Element 12
        2872310693891620498ULL,
        18442687036345179693ULL,
        12600134693347240975ULL,
        // Element 13
        15762660494228645950ULL,
        1089223122280328124ULL,
        12538857081211527031ULL,
        // Element 14
        3260775988529739921ULL,
        3467800841604774028ULL,
        5041750969204501126ULL,
        // Element 15
        10368294881249253002ULL,
        12894191081247816755ULL,
        16792827882436518814ULL
    };

    /// Expected grinding nonce (proof-of-work result).
    /// This value satisfies: hash(challenge || nonce) has POW_BITS leading zeros.
    constexpr uint64_t EXPECTED_NONCE = 56;

    /// Expected Poseidon2 hash of EXPECTED_FINAL_POL (4 Goldilocks elements).
    /// Computed using Poseidon2Goldilocks<16>::linear_hash_seq over all 48 elements.
    constexpr std::array<uint64_t, 4> EXPECTED_FINAL_POL_HASH = {
        16201618454940366509ULL,
        9223689653289312170ULL,
        6707438330426141909ULL,
        10762121192969877648ULL
    };

    /// SHA256 checksum of EXPECTED_FINAL_POL as comma-separated decimal strings.
    /// Used for quick validation without element-by-element comparison.
    constexpr const char* const EXPECTED_FINAL_POL_CHECKSUM =
        "45f67c58cbbac0383eb7d29cef8e93a12a18aa5520dc3a346369b6dacaedf921";

}  // namespace SimpleLeft

/**
 * Lookup2_12: More complex AIR with 4096 rows (2^12)
 *
 * This AIR tests lookup operations with significantly more rows than SimpleLeft.
 * It exercises FRI folding over larger traces, which requires more folding steps.
 */
namespace Lookup2_12 {

    //=========================================================================
    // FRI Configuration (from Lookup2_12.starkinfo.json)
    //=========================================================================

    /// Base domain size: 2^N_BITS = 4096 rows
    constexpr uint64_t N_BITS = 12;

    /// Extended domain size: 2^N_BITS_EXT (with blowup factor)
    constexpr uint64_t N_BITS_EXT = 13;

    /// Number of FRI queries for soundness
    constexpr uint64_t N_QUERIES = 228;

    /// Proof-of-work grinding bits
    constexpr uint64_t POW_BITS = 16;

    /// Merkle tree branching factor
    constexpr uint64_t MERKLE_ARITY = 4;

    /// Transcript (Fiat-Shamir) arity
    constexpr uint64_t TRANSCRIPT_ARITY = 4;

    /// FRI step configuration: 3 steps for larger polynomial reduction
    constexpr uint64_t NUM_FRI_STEPS = 3;

    /// FRI challenges at each folding step (captured from C++)
    constexpr std::array<std::array<uint64_t, 3>, 3> FRI_CHALLENGES = {{
        {17372316241482201106ULL, 4573882784057680491ULL, 7695471256808767655ULL},   // Challenge 0
        {12021750080465063677ULL, 6684995858571836146ULL, 10210747538308341014ULL},  // Challenge 1
        {3248307857335837549ULL, 18262011665847589529ULL, 15352170406680365981ULL}   // Challenge 2
    }};

    //=========================================================================
    // Expected FRI Output (from Lookup2_12_2.json)
    //=========================================================================

    /// Final polynomial after all FRI folding steps.
    /// Structure: 32 cubic extension elements = 96 Goldilocks field elements.
    constexpr std::array<uint64_t, 96> EXPECTED_FINAL_POL = {
        // Element 0
        14434583126679987313ULL,
        5482150761621168896ULL,
        3249328641526182044ULL,
        // Element 1
        15342740250347407991ULL,
        3376553363229461591ULL,
        4257268957549436242ULL,
        // Element 2
        7204487384040872062ULL,
        1419173031459822675ULL,
        2061249537966676017ULL,
        // Element 3
        2360586269179456038ULL,
        15376369807336137918ULL,
        9353401887418425164ULL,
        // Element 4
        10412156313889373274ULL,
        3591314333206605595ULL,
        4803765269341221341ULL,
        // Element 5
        5033644672118612008ULL,
        7219991869283703241ULL,
        5001325043480604972ULL,
        // Element 6
        15948725184182871707ULL,
        15522723472618604735ULL,
        9907990838610836609ULL,
        // Element 7
        9470319161037913018ULL,
        17268345614200704752ULL,
        3654202055025360269ULL,
        // Element 8
        13100866642308064996ULL,
        17341759162511200959ULL,
        7319519320015423486ULL,
        // Element 9
        12084612760618137204ULL,
        7454792536055106792ULL,
        2659215907969302634ULL,
        // Element 10
        197416323470751095ULL,
        4767691990383163790ULL,
        6429445215664945539ULL,
        // Element 11
        15599679625630644600ULL,
        10704837000018217994ULL,
        14619111704412444750ULL,
        // Element 12
        15879145559683750116ULL,
        10806891138089601907ULL,
        6398240568623563867ULL,
        // Element 13
        14868897281419723370ULL,
        924837540248075600ULL,
        13479315813292439965ULL,
        // Element 14
        11860535291544263725ULL,
        9525832088029768261ULL,
        1056937185540367752ULL,
        // Element 15
        9242712766516462579ULL,
        3678973432283065878ULL,
        6246989568381022564ULL,
        // Element 16
        3986523664812881640ULL,
        15175234450602730740ULL,
        12905501262580237230ULL,
        // Element 17
        10705369138838456284ULL,
        10702382605332658692ULL,
        7629631655928945403ULL,
        // Element 18
        9262724744720817643ULL,
        15887564237035175821ULL,
        9968888681798946160ULL,
        // Element 19
        5157862280797414087ULL,
        15846645308041041927ULL,
        14044103179964922718ULL,
        // Element 20
        7541286177638753403ULL,
        9959371914069074779ULL,
        4742210589618127119ULL,
        // Element 21
        8945694359776425999ULL,
        5857016951276199961ULL,
        15956542795161863896ULL,
        // Element 22
        5097832630748515311ULL,
        2805433767902235137ULL,
        14156619039058681370ULL,
        // Element 23
        5359383358562328040ULL,
        10696011412389368858ULL,
        14259441144882985156ULL,
        // Element 24
        10562871434525600334ULL,
        2950782197354151668ULL,
        5287728438265398672ULL,
        // Element 25
        4179399445730488462ULL,
        699779008451773962ULL,
        6724499112382485659ULL,
        // Element 26
        17736390686191080988ULL,
        6782110977108258102ULL,
        9204523493687027062ULL,
        // Element 27
        6821914454530953253ULL,
        14820845627046358896ULL,
        12893257468286467420ULL,
        // Element 28
        4125657212508052294ULL,
        11795123797861066031ULL,
        2646944690559974986ULL,
        // Element 29
        8386604238912971683ULL,
        12635389879257946431ULL,
        788283794214107156ULL,
        // Element 30
        9665347948841523245ULL,
        10612365642456120293ULL,
        15820909052152390155ULL,
        // Element 31
        5010386192355180209ULL,
        7162751007858926896ULL,
        2839955806073769762ULL
    };

    /// Expected grinding nonce (proof-of-work result).
    constexpr uint64_t EXPECTED_NONCE = 33180;

    /// Hash of FRI input polynomial (before folding).
    /// Full polynomial is 6144 values - only hash stored for validation.
    constexpr std::array<uint64_t, 4> FRI_INPUT_POL_HASH = {
        17943519307791263320ULL,
        8481871866231913591ULL,
        16776450438768947771ULL,
        3492680947335154131ULL
    };

    /// Expected Poseidon2 hash of EXPECTED_FINAL_POL (4 Goldilocks elements).
    constexpr std::array<uint64_t, 4> EXPECTED_FINAL_POL_HASH = {
        16724271852290172135ULL,
        167123672743506872ULL,
        85739372367436007ULL,
        15077976899410783742ULL
    };

}  // namespace Lookup2_12

}  // namespace FriPinningVectors

#endif  // FRI_PINNING_VECTORS_HPP
