"""
Proof loader for C++ generated FRI proofs.

This module provides functionality to load and parse proof JSON files
generated by the C++ implementation, enabling cross-validation between
Python and C++ implementations.

C++ Proof Format Reference: proofman/src/starkpil/proof_serializer.hpp
"""

import json
import os
from typing import Dict, List, Any, Optional
from dataclasses import dataclass


@dataclass
class FriProofData:
    """
    Parsed FRI proof data from C++ generated JSON.

    This structure mirrors the JSON proof format used by the C++ implementation.
    """
    # Final polynomial after all FRI folding steps
    # Format: List of cubic extension elements, each element is [c0, c1, c2]
    final_pol: List[List[int]]

    # Grinding nonce (proof-of-work result)
    nonce: int

    # Merkle roots for each stage (root1, root2, root3)
    roots: List[List[int]]

    # Airgroup values (accumulated values)
    airgroup_values: List[List[int]]

    # Polynomial evaluations at opening points
    evals: List[List[int]]

    # Query proof data
    query_proofs: Dict[str, Any]

    # Source file path (for debugging)
    source_path: str

    @property
    def final_pol_flat(self) -> List[int]:
        """Return final polynomial as flat list of Goldilocks elements."""
        result = []
        for elem in self.final_pol:
            result.extend(elem)
        return result

    @property
    def num_cubic_elements(self) -> int:
        """Number of cubic extension elements in final polynomial."""
        return len(self.final_pol)

    @property
    def num_goldilocks_elements(self) -> int:
        """Number of Goldilocks elements in final polynomial."""
        return len(self.final_pol) * 3


def load_proof(path: str) -> FriProofData:
    """
    Load and parse a C++ generated proof JSON file.

    Args:
        path: Path to the proof JSON file

    Returns:
        Parsed FriProofData structure

    Raises:
        FileNotFoundError: If proof file doesn't exist
        ValueError: If proof structure is invalid
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"Proof file not found: {path}")

    with open(path, 'r') as f:
        data = json.load(f)

    # Validate required fields
    required_fields = ['finalPol', 'nonce', 'root1', 'root2', 'root3']
    for field in required_fields:
        if field not in data:
            raise ValueError(f"Proof missing required field: {field}")

    # Parse final polynomial (convert string values to integers)
    final_pol = []
    for elem in data['finalPol']:
        if len(elem) != 3:
            raise ValueError(f"finalPol element should have 3 components, got {len(elem)}")
        final_pol.append([int(v) for v in elem])

    # Parse nonce
    nonce = int(data['nonce'])

    # Parse roots
    roots = []
    for root_key in ['root1', 'root2', 'root3']:
        if root_key in data:
            roots.append([int(v) for v in data[root_key]])

    # Parse airgroup values
    airgroup_values = []
    if 'airgroupvalues' in data:
        for val in data['airgroupvalues']:
            airgroup_values.append([int(v) for v in val])

    # Parse evaluations
    evals = []
    if 'evals' in data:
        for val in data['evals']:
            evals.append([int(v) for v in val])

    # Collect query proofs (s0_* fields)
    query_proofs = {}
    for key, value in data.items():
        if key.startswith('s0_'):
            query_proofs[key] = value

    return FriProofData(
        final_pol=final_pol,
        nonce=nonce,
        roots=roots,
        airgroup_values=airgroup_values,
        evals=evals,
        query_proofs=query_proofs,
        source_path=path
    )


def find_proof_file(test_name: str, base_dir: Optional[str] = None) -> Optional[str]:
    """
    Find proof file for a given test AIR.

    Searches standard locations used by generate-fri-vectors.sh and test-pinning.sh.

    Args:
        test_name: AIR name ('SimpleLeft_0', 'Lookup2_12_2', etc.)
        base_dir: Base directory for search (defaults to pil2-proofman root)

    Returns:
        Path to proof file if found, None otherwise
    """
    if base_dir is None:
        # Find the pil2-proofman root directory
        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    # Determine test subdirectory from AIR name
    if 'SimpleLeft' in test_name or 'SimpleRight' in test_name:
        test_subdir = 'simple'
    elif 'Lookup' in test_name:
        test_subdir = 'lookup'
    else:
        test_subdir = 'simple'  # Default

    # Standard search locations
    search_paths = [
        f"pil2-components/test/{test_subdir}/build/fri_vectors_output/proofs/{test_name}.json",
        f"pil2-components/test/{test_subdir}/build/pinning_test_output/proofs/{test_name}.json",
    ]

    for rel_path in search_paths:
        full_path = os.path.join(base_dir, rel_path)
        if os.path.exists(full_path):
            return full_path

    return None


def detect_air_type(proof_path: str) -> str:
    """
    Detect AIR type from proof file path.

    Args:
        proof_path: Path to proof file

    Returns:
        AIR type identifier ('simple', 'lookup', 'unknown')
    """
    if 'SimpleLeft' in proof_path:
        return 'simple'
    elif 'Lookup2_12' in proof_path:
        return 'lookup'
    else:
        return 'unknown'
